import {defineField,defineType} from 'sanity';
const status=[{title:'Delivered',value:'delivered'},{title:'In Progress',value:'in-progress'},{title:'Ongoing',value:'ongoing'},{title:'System Architecture',value:'architecture'},{title:'Concept',value:'concept'}];
export default defineType({name:'project',title:'Project',type:'document',fields:[
 defineField({name:'title',type:'string',validation:(Rule)=>Rule.required()}),defineField({name:'slug',type:'slug',options:{source:'title'},validation:(Rule)=>Rule.required()}),defineField({name:'client',title:'Client / company',type:'string'}),defineField({name:'industry',type:'string'}),defineField({name:'category',type:'string',validation:(Rule)=>Rule.required()}),defineField({name:'status',type:'string',description:'Use only when the project status is known and approved for publication.',options:{list:status,layout:'dropdown'}}),defineField({name:'year',type:'number',validation:(Rule)=>Rule.integer().min(2000).max(2100)}),
 defineField({name:'summary',title:'Short summary',type:'text',rows:3,validation:(Rule)=>Rule.required()}),defineField({name:'featured',type:'boolean',initialValue:false}),defineField({name:'featuredOrder',title:'Featured order',type:'number',validation:(Rule)=>Rule.integer().min(1)}),defineField({name:'order',title:'Portfolio order',type:'number',validation:(Rule)=>Rule.integer().min(1)}),
 defineField({name:'visibility',title:'Portfolio visibility',type:'string',options:{list:[{title:'Card only',value:'card-only'},{title:'Full case study',value:'case-study'},{title:'Draft',value:'draft'}],layout:'radio'},initialValue:'draft',validation:(Rule)=>Rule.required()}),defineField({name:'role',type:'string'}),defineField({name:'services',type:'array',of:[{type:'string'}]}),defineField({name:'technologies',type:'array',of:[{type:'reference',to:[{type:'technology'}]}]}),
 defineField({name:'problem',title:'The problem',type:'text',rows:5}),defineField({name:'businessContext',title:'Business context',type:'text',rows:5}),defineField({name:'solution',title:'Solution / system',type:'text',rows:5}),defineField({name:'workflow',title:'Workflow / architecture',type:'array',of:[{type:'string'}]}),defineField({name:'implementation',type:'array',of:[{type:'implementationItem'}]}),defineField({name:'outcomes',type:'array',description:'Add qualitative outcomes only when factually supported.',of:[{type:'string'}]}),defineField({name:'metrics',type:'array',description:'Only verified metrics render publicly.',of:[{type:'metric'}]}),defineField({name:'testimonial',type:'reference',to:[{type:'testimonial'}]}),
 defineField({name:'coverImage',title:'Cover image',type:'image',options:{hotspot:true},description:'Recommended for public cards and case studies. Review for private information before publishing.',fields:[{name:'altText',type:'string',title:'Alt text',validation:(Rule)=>Rule.required()}]}),defineField({name:'screenshots',type:'array',description:'Review screenshots for emails, phone numbers, customer or patient records, health/banking information, credentials, access tokens, internal notes, private IDs, and PII.',of:[{type:'projectScreenshot'}]}),defineField({name:'seoTitle',title:'SEO title',type:'string'}),defineField({name:'seoDescription',title:'SEO description',type:'text',rows:3}),
],preview:{select:{title:'title',category:'category',status:'status',visibility:'visibility',media:'coverImage'},prepare:({title,category,status,visibility,media})=>({title,subtitle:[category,status,visibility].filter(Boolean).join(' · '),media})}});
